#!/bin/bash

# Employee Leave Management System - Quick Start Guide

echo "========================================="
echo "Employee Leave Management System"
echo "========================================="
echo ""

echo "This system requires:"
echo "1. MySQL database running on localhost:3306"
echo "2. Java 17+ installed"
echo "3. Node.js 16+ installed"
echo "4. Maven installed"
echo ""

echo "Setup Steps:"
echo ""
echo "Step 1: Create MySQL Database"
echo "-------------------------------"
echo "mysql -u root -p"
echo "CREATE DATABASE leave_management_db;"
echo "exit"
echo ""

echo "Step 2: Start Backend (in new terminal)"
echo "----------------------------------------"
echo "cd backend"
echo "mvn clean install"
echo "mvn spring-boot:run"
echo ""

echo "Step 3: Start Frontend (in new terminal)"
echo "-----------------------------------------"
echo "cd frontend"
echo "npm install"
echo "npm run dev"
echo ""

echo "Step 4: Access Application"
echo "--------------------------"
echo "Frontend: http://localhost:3000"
echo "Backend:  http://localhost:8080"
echo ""

echo "Step 5: Register Demo Users"
echo "---------------------------"
echo "Register an Employee account:"
echo "  - Username: employee"
echo "  - Password: password"
echo "  - Role: Employee"
echo ""
echo "Register a Manager account:"
echo "  - Username: manager"
echo "  - Password: password"
echo "  - Role: Manager"
echo ""

echo "========================================="
echo "Features:"
echo "========================================="
echo "Employee:"
echo "  ✓ Apply for leave"
echo "  ✓ View leave history"
echo "  ✓ Track leave balance"
echo "  ✓ Cancel pending requests"
echo ""
echo "Manager:"
echo "  ✓ View all leave requests"
echo "  ✓ Approve/reject requests"
echo "  ✓ Add comments"
echo "  ✓ View pending dashboard"
echo ""
echo "========================================="
